project:
  type: website
  output-dir: 'docs'
  

website:
  title: "Efficient Programming with R: A Workshop"
  body-footer: <text style="text-align:center">ForeSITE</text>
  repo-url: https://github.com/EpiForeSITE/efficient-r-foresite
  repo-actions: [edit, source]
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
      - text: Contents
        menu:
        - href: profiling.qmd
        - href: data.table.qmd
          text: The data.table R package
        - href: parallel.qmd
          text: Parallel Computing
        - href: parallel_pkg.qmd
          text: Parallel Packages
    right:
      - participants.qmd
      - text: Git
        menu: 
        - href: https://epiforesite.github.io/r-pkgs-workshop/git/slides.html
          text: Intro to Git slides
        - href: https://epiforesite.github.io/r-pkgs-workshop/git/lab.html
          text: Intro to Git lab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto
